create table settings (
  id int primary key default 1 check (id = 1),
  business_name text not null default 'JJ Visuals',
  address text not null default 'Blk 296A Compassvale Crescent #10-293, S541296',
  phone text not null default '+65 9656 1716',
  email text not null default 'chuajiajun2705@gmail.com',
  paynow_number text not null default '+6596561716',
  payee_name text not null default 'Chua Jia Jun',
  bank_details text not null default 'Bank Name: DBS',
  payment_terms text not null default 'paynow within 30 days of invoice',
  invoice_prefix text not null default 'A-',
  next_invoice_seq int not null default 30
);
insert into settings (id) values (1);

create table customers (
  id int generated by default as identity (start with 9) primary key,
  name text not null,
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  created_at timestamptz not null default now()
);

create table presets (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null default '',
  unit_price_cents int not null,
  default_qty numeric not null default 1,
  created_at timestamptz not null default now()
);

create table invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text unique,
  status text not null default 'draft' check (status in ('draft','unpaid','paid')),
  issue_date date not null default current_date,
  customer_id int references customers(id),
  job_event text not null default '',
  job_date text not null default '',
  job_location text not null default '',
  line_items jsonb not null default '[]',
  discount_type text not null default 'none' check (discount_type in ('none','amount','percent')),
  discount_value numeric not null default 0,
  subtotal_cents int not null default 0,
  total_cents int not null default 0,
  paid_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- RLS: owner-only on every table
alter table settings enable row level security;
alter table customers enable row level security;
alter table presets enable row level security;
alter table invoices enable row level security;

create policy owner_settings on settings for all to authenticated
  using ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com')
  with check ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com');
create policy owner_customers on customers for all to authenticated
  using ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com')
  with check ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com');
create policy owner_presets on presets for all to authenticated
  using ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com')
  with check ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com');
create policy owner_invoices on invoices for all to authenticated
  using ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com')
  with check ((select auth.jwt()->>'email') = 'chuajiajun2705@gmail.com');

-- Atomically claim the next invoice number and finalize a draft
create or replace function finalize_invoice(inv_id uuid)
returns text
language plpgsql
security invoker
as $$
declare
  num text;
begin
  update settings
     set next_invoice_seq = next_invoice_seq + 1
   where id = 1
  returning invoice_prefix || (next_invoice_seq - 1)::text into num;

  update invoices
     set invoice_number = num, status = 'unpaid', updated_at = now()
   where id = inv_id and status = 'draft';

  if not found then
    raise exception 'invoice % is not a draft', inv_id;
  end if;

  return num;
end;
$$;
