-- supabase/migrations/005_customer_number_cascade.sql
-- Let the owner change a customer's client number (customers.id). Old
-- clients entered after the fact otherwise get high auto-assigned ids that
-- read as "newer" than they are. customers.id is `generated by default as
-- identity` (starts at 9), so ids 1-8 are free to assign by hand.
--
-- invoices.customer_id references customers(id) with the default NO ACTION,
-- which would block any id change on a customer that has invoices. Recreate
-- the FK with ON UPDATE CASCADE so a client-number change atomically follows
-- through to that customer's invoices. ON DELETE stays NO ACTION (deleting a
-- customer with invoices should still be blocked).

alter table invoices drop constraint invoices_customer_id_fkey;
alter table invoices add constraint invoices_customer_id_fkey
  foreign key (customer_id) references customers(id) on update cascade;
